require:
  - rubocop-rspec
  - 'test_prof/rubocop'
  - './lib/rubocop/cop/lint/env'

AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'lib/templates/**/**'
    - 'lib/scripts/**/**'
    - 'tmp/**/*'
    - 'Vagrantfile'
    - 'node_modules/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.5

RSpec/AggregateFailures:
  Include:
    - 'spec/**/*.rb'
  Exclude:
    - 'spec/models/**/*.rb'
    - 'spec/forms/**/*.rb'
    - 'spec/services/**/*.rb'

RSpec/LeadingSubject:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Capybara/FeatureMethods:
  Enabled: false

Lint/Env:
  Enabled: true
  Exclude:
    - 'lib/tasks/**/*'
    - 'config/environments/**/*'
    - 'config/*.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/**/*'
    - 'Rakefile'
    - 'Gemfile'

Rails:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 80
  Exclude:
    - spec/**/*
Metrics/MethodLength:
  Enabled: true
  Max: 15
  Exclude:
    - spec/**/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/AbcSize:
  Exclude:
    - spec/**/*

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  Enabled: false
